FIGS = \
chap02-1.pdf chap02-1.png \
chap02-2.pdf chap02-2.png  \
chap02-3.pdf chap02-3.png  \
chap02-4.pdf chap02-4.png  \
chap02-5.pdf chap02-5.png  \
chap02-6.pdf chap02-6.png  \
chap03-1.pdf chap03-1.png  \
chap03-2.pdf chap03-2.png  \
chap03-3.pdf chap03-3.png  \
chap04-1.pdf chap04-1.png  \
chap04-2.pdf chap04-2.png  \
chap04-3.pdf chap04-3.png  \
chap04-4.pdf chap04-4.png  \
chap04-5.pdf chap04-5.png  \
chap05-1.pdf chap05-1.png  \
chap05-2.pdf chap05-2.png  \
chap05-3.pdf chap05-3.png  \
chap05-4.pdf chap05-4.png  \
chap05-5.pdf chap05-5.png  \
chap05-6.pdf chap05-6.png  \
chap06-1.pdf chap06-1.png  \
chap06-2.pdf chap06-2.png  \
chap06-3.pdf chap06-3.png  \
chap06-4.pdf chap06-4.png  \
chap06-5.pdf chap06-5.png  \
chap07-1.pdf chap07-1.png  \
chap07-2.pdf chap07-2.png  \
chap07-3.pdf chap07-3.png  \
chap07-4.pdf chap07-4.png  \
chap07-5.pdf chap07-5.png  \
chap07-6.pdf chap07-6.png  \
chap07-7.pdf chap07-7.png  \
chap07-8.pdf chap07-8.png  \
chap07-9.pdf chap07-9.png  \
chap08-1.pdf chap08-1.png  \
chap08-2.pdf chap08-2.png  \
chap08-3.pdf chap08-3.png  \
chap08-4.pdf chap08-4.png  \
chap08-5.pdf chap08-5.png  \
chap08-6.pdf chap08-6.png  \
chap09-1.pdf chap09-1.png  \
chap09-2.pdf chap09-2.png  \
chap09-3.pdf chap09-3.png  \
chap09-4.pdf chap09-4.png  \
chap09-5.pdf chap09-5.png  \
chap10-1.pdf chap10-1.png  \
chap10-2.pdf chap10-2.png  \
chap11-1.pdf chap11-1.png  \
chap11-2.pdf chap11-2.png  \
chap11-3.pdf chap11-3.png  \
chap11-4.pdf chap11-4.png  \
chap11-5.pdf chap11-5.png  \
chap11-6.pdf chap11-6.png  \
chap12-1.pdf chap12-1.png  \
chap12-2.pdf chap12-2.png  \

FIGDEST = ../book/figs

figs:
	rsync -a $(FIGS) $(FIGDEST)

chap05figs:
	epstopdf chap05-1.eps
	epstopdf chap05-2.eps
	epstopdf chap05-3.eps
	epstopdf chap05-4.eps
	epstopdf chap05-5.eps
	epstopdf chap05-6.eps
